name: ${PROJECT_NAME}

networks:
  apinet: {}
  backnet:
    internal: true
  dbnet:
    internal: true

services:
  traefik:
    image: traefik:v3.1
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--providers.docker=false"
      - "--entrypoints.vpn.address=:80"
      - "--log.level=${TRAEFIK_LOG_LEVEL}"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
    networks: [ apinet ]
    ports:
      - "${TRAEFIK_BIND_IP}:80:80"
    environment:
      - TZ=${TZ}

  wg_vpn:
    image: lscr.io/linuxserver/wireguard
    cap_add: [ NET_ADMIN ]
    devices:
      - /dev/net/tun
    volumes:
      - ./wg:/config   # внутри должен быть wg0.conf
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    networks: [ apinet, backnet ]

  api_father:
    build: ./api_father
    depends_on: [ wg_vpn ]
    networks: [ backnet, dbnet ]
    environment:
      - TZ=${TZ}
      - REDIS_URL=${REDIS_URL}
      - QUEUE_REQUESTS=${QUEUE_REQUESTS}
      - QUEUE_EVENTS=${QUEUE_EVENTS}
      - DB_MODE=${DB_MODE}
      - DB_TEST_HOST=${DB_TEST_HOST}
      - DB_TEST_PORT=${DB_TEST_PORT}
      - DB_TEST_NAME=${DB_TEST_NAME}
      - DB_TEST_USER=${DB_TEST_USER}
      - DB_TEST_PASSWORD=${DB_TEST_PASSWORD}
      - DB_PROD_HOST=${DB_PROD_HOST}
      - DB_PROD_PORT=${DB_PROD_PORT}
      - DB_PROD_NAME=${DB_PROD_NAME}
      - DB_PROD_USER=${DB_PROD_USER}
      - DB_PROD_PASSWORD=${DB_PROD_PASSWORD}

  api_father_redis:
    image: redis:7
    networks: [ backnet ]

  worker:
    build: ./worker
    depends_on: [ api_father_redis ]
    networks: [ backnet ]
    environment:
      - REDIS_URL=${REDIS_URL}
      - QUEUE_REQUESTS=${QUEUE_REQUESTS}
