services:
  api_1:
    build: ./api_1
    network_mode: "service:wg_vpn"
    depends_on: [ wg_vpn, api_father ]
    environment:
      - TZ=${TZ}
      - API_FATHER_URL=http://api_father:9000

  api_2:
    build: ./api_2
    network_mode: "service:wg_vpn"
    depends_on: [ wg_vpn, api_father ]
    environment:
      - TZ=${TZ}
      - API_FATHER_URL=http://api_father:9000

  api_3:
    build: ./api_3
    network_mode: "service:wg_vpn"
    depends_on: [ wg_vpn, api_father ]
    environment:
      - TZ=${TZ}
      - API_FATHER_URL=http://api_father:9000
