services:
  db:
    image: mysql:8.0.42
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_TEST_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_TEST_NAME}
      MYSQL_USER: ${DB_TEST_USER}
      MYSQL_PASSWORD: ${DB_TEST_PASSWORD}
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_0900_ai_ci"
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro
    networks: [ dbnet ]
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 10s
      retries: 10

  migrator:
    image: flyway/flyway:10
    depends_on: [ db ]
    networks: [ dbnet ]
    entrypoint: [ "sh", "-lc",
      "test '${MIGRATE_ON_START_TEST}' = '1' && \
       flyway -url=jdbc:mysql://db:${DB_TEST_PORT}/${DB_TEST_NAME} \
              -user=${DB_TEST_USER} -password=${DB_TEST_PASSWORD} \
              -connectRetries=60 -locations=filesystem:/flyway/sql migrate || true"
    ]
    volumes:
      - ./db/migrations:/flyway/sql:ro

volumes:
  dbdata:

